
// Requests
export const LOAD_REQUESTS = 'LOAD_REQUESTS';
export const REQUESTS_LOADED = 'REQUESTS_LOADED';
export const LOAD_REQUESTS_FAILED = 'LOAD_REQUESTS_FAILED';
export const SELECT_REQUEST = 'SELECT_REQUEST';
export const REQUEST_SELECTION_LOADED = 'REQUEST_SELECTION_LOADED';
export const CLEAR_REQUEST_SELECTION = 'CLEAR_REQUEST_SELECTION';
export const SELECT_REQUEST_FAILED = 'LOAD_REQUEST_FAILED';
export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';
export const TOGGLE_ALL_REQUESTS = 'TOGGLE_ALL_REQUESTS';


// Lists
export const LOAD_LISTS = 'LOAD_LISTS';
export const LISTS_LOADED = 'LISTS_LOADED';
export const LOAD_LISTS_FAILED = 'LOAD_LISTS_FAILED';
export const TOGGLE_LIST_SELECTION = 'TOGGLE_LIST_SELECTION';
export const CLEAR_LIST_SELECTION = 'CLEAR_LIST_SELECTION';
export const OPEN_ITEM_ADD_FORM = 'OPEN_ITEM_ADD_FORM';
export const OPEN_ITEM_EDIT_FORM = 'OPEN_ITEM_EDIT_FORM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const CONFIRM_LIST_ITEM_EDIT = 'CONFIRM_LIST_ITEM_EDIT';
export const CANCEL_LIST_ITEM_EDIT = 'CANCEL_LIST_ITEM_EDIT';
export const OPEN_SAVE_LIST_DIALOG = 'OPEN_SAVE_LIST_DIALOG';
export const CLOSE_SAVE_LIST_DIALOG = 'CLOSE_SAVE_LIST_DIALOG';
export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_LIST_COMPLETE = 'UPDATE_LIST_COMPLETE';
export const UPDATE_LIST_FAILED = 'UPDATE_LIST_FAILED';
export const MOVE_LIST_ITEM = 'MOVE_LIST_ITEM';


// Statuses
export const LOAD_STATUSES = 'LOAD_STATUSES';
export const STATUSES_LOADED = 'STATUSES_LOADED';
export const LOAD_STATUSES_FAILED = 'LOAD_STATUSES_FAILED';


// Actions
export const LOAD_ACTIONS = 'LOAD_ACTIONS';
export const ACTIONS_LOADED = 'ACTIONS_LOADED';
export const LOAD_ACTIONS_FAILED = 'LOAD_ACTIONS_FAILED';

export const LOAD_TIMES_OF_DAY = 'LOAD_TIMES_OF_DAY';
export const TIMES_OF_DAY_LOADED = 'TIMES_OF_DAY_LOADED';
export const LOAD_TIMES_OF_DAY_FAILED = 'LOAD_TIMES_OF_DAY_FAILED';

// Events
export const OPEN_SUBMIT_DIALOG = 'OPEN_SUBMIT_DIALOG';
export const CLOSE_SUBMIT_DIALOG = 'CLOSE_SUBMIT_DIALOG';
export const SUBMIT_EVENT = 'SUBMIT_EVENT';
export const EVENT_SUBMIT_COMPLETE = 'EVENT_SUBMIT_COMPLETE';
export const EVENT_SUBMIT_FAILED = 'EVENT_SUBMIT_FAILED';
