
// Main
export const SET_TAB = 'SET_TAB';


// Requests
export const LOAD_REQUESTS = 'LOAD_REQUESTS';
export const REQUESTS_LOADED = 'REQUESTS_LOADED';
export const LOAD_REQUESTS_FAILED = 'LOAD_REQUESTS_FAILED';
export const SELECT_REQUEST = 'SELECT_REQUEST';
export const REQUEST_SELECTION_LOADED = 'REQUEST_SELECTION_LOADED';
export const CLEAR_REQUEST_SELECTION = 'CLEAR_REQUEST_SELECTION';
export const SELECT_REQUEST_FAILED = 'LOAD_REQUEST_FAILED';
export const TOGGLE_REQUEST = 'TOGGLE_REQUEST';
export const TOGGLE_ALL_REQUESTS = 'TOGGLE_ALL_REQUESTS';


// Lists
export const LOAD_LISTS = 'LOAD_LISTS';
export const LISTS_LOADED = 'LISTS_LOADED';
export const LOAD_LISTS_FAILED = 'LOAD_LISTS_FAILED';
export const TOGGLE_LIST_SELECTION = 'TOGGLE_LIST_SELECTION';
export const CLEAR_LIST_SELECTION = 'CLEAR_LIST_SELECTION';


// Events
export const LOAD_EVENTS = 'LOAD_EVENTS';
export const EVENTS_LOADED = 'EVENTS_LOADED';
export const LOAD_EVENTS_FAILED = 'LOAD_EVENTS_FAILED';
