
// Main
export const SET_TAB = 'SET_TAB';

// Requests
export const LOAD_REQUESTS = 'LOAD_REQUESTS';
export const REQUESTS_LOADED = 'REQUESTS_LOADED';
export const LOAD_REQUESTS_FAILED = 'LOAD_REQUESTS_FAILED';
export const SELECT_REQUEST = 'SELECT_REQUEST';
export const REQUEST_SELECTION_LOADED = 'REQUEST_SELECTION_LOADED';
export const SELECT_REQUEST_FAILED = 'LOAD_REQUEST_FAILED';


// Lists
export const LOAD_LISTS = 'LOAD_LISTS';
export const LISTS_LOADED = 'LISTS_LOADED';
export const LOAD_LISTS_FAILED = 'LOAD_LISTS_FAILED';
