class _Config(object):
    DEBUG = True

    FBSL_CATCH_ALL_LIST = "Family of 5+"
    FBSL_EVENTS_CACHE_EXPIRY_SECONDS = 0
    FBSL_LISTS_CACHE_EXPIRY_SECONDS = 0
    FBSL_REQUESTS_CACHE_EXPIRY_SECONDS = 0
    FBSL_SA_KEY_FILE_PATH = "foodbank-southlondon-ecd573527735.json"

    ERROR_404_HELP = False
    RESTX_VALIDATE = True


class DevelopmentConfig(_Config):
    FBSL_EVENTS_CACHE_EXPIRY_SECONDS = 60
    FBSL_EVENTS_GSHEET_URI = "1GfD-YA_9eMSMqu9eTZlCEC0wvsV6c0CRlMLRPOvWM48"
    FBSL_LISTS_CACHE_EXPIRY_SECONDS = 0
    FBSL_LISTS_GSHEET_URI = "1Hor0i7K_W99LFXw-Grpf1mIY2MjDUNGnfV2ByNGf1gQ"
    FBSL_REQUESTS_CACHE_EXPIRY_SECONDS = 60
    FBSL_REQUESTS_FORM_URI = "1opR0xwrjeHD3ra0ZXhtHUq_dRGP7edSSMCt3dT-zXWg"
    FBSL_REQUESTS_GSHEET_URI = "1eMiA6DAYmYJVYwNvxj18yRiSBImCXu6WiCD-4CqM7P8"


class ProductionConfig(_Config):
    FBSL_EVENTS_CACHE_EXPIRY_SECONDS = 3600
    FBSL_LISTS_CACHE_EXPIRY_SECONDS = 0
    FBSL_REQUESTS_CACHE_EXPIRY_SECONDS = 300


CONFIGURATIONS = {
    None: _Config,
    "dev": DevelopmentConfig,
    "prod": ProductionConfig
}
